name: Java CI with Maven

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v4

    - name: 2. Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: 3. Compile Source Code
      run: mvn -B compile --file pom.xml

    - name: 4. Run Unit Tests (JUnit)
      run: mvn -B test --file pom.xml

    - name: 5. Generate JaCoCo Coverage Report
      run: mvn -B jacoco:report --file pom.xml

    - name: 6. Package Application JAR
      run: mvn -B package -DskipTests --file pom.xml

    - name: 7. Upload Application Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/app.jar
        retention-days: 7

    - name: 8. Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-coverage-report
        path: target/site/jacoco/
        retention-days: 7

    - name: 9. Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: surefire-test-results
        path: target/surefire-reports/
        retention-days: 7
